name: .NET Core

on:
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108
    - name: Build with dotnet
      run: |
        cd ./EditoolsUnity/EditoolsUnity
        dotnet build --configuration Release
    - name: Build with dotnet
      run: |
        cd ./EditoolsUnity
        ls -l
        cd ./EditoolsUnity
        ls -l
        cd ./bin
        ls -l
        cd ./Release
        ls -l
        cd ./netstandard2.0
        ls -l
    - name: create release
      run: |
        set -x
        assets=()
        assets+=("-a" "EditoolsUnity.dll")
        tag_name="${TAG_NAME##*/}"
        hub release create "${assets[@]}" -m "$tag_name" "$tag_name"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TAG_NAME: "EditoolsUnity"
    
