name: .NET Core

on:
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108
    - name: Build with dotnet
      run: |
        cd ./EditoolsUnity/EditoolsUnity
        dotnet build --configuration Release
    - name: Build with dotnet
      run: |
        cd ./EditoolsUnity
        ls -l
        cd ./EditoolsUnity
        ls -l
        cd ./bin
        ls -l
        cd ./Release
        ls -l
        cd ./netstandard2.0
        ls -l
    - name: release
      uses: actions/create-release@v1
      id: create_release
      with:
        draft: false
        prerelease: false
        release_name: Editoolsnity
        tag_name: ${{ github.ref }} 
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TAG_NAME: "EditoolsUnity"

    - name: upload assets
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
         upload_url: ${{ steps.create_release.outputs.upload_url }}
         asset_path: ./EditoolsUnity/EditoolsUnity/bin/Release/netstandard2.0/EditoolsUnity.dll
         asset_name: EditoolsUnity.dll
